// 60 Complete Realistic Commercial & Passenger Vehicles for 3BrosMotor Dealership Inventory
// Matching the 60 vehicles in stock from the admin dashboard

export const INITIAL_60_VEHICLES = [
  {
    id: '1001',
    make: 'Toyota',
    model: 'Hilux Revo 4WD',
    year: '2022',
    chassis: 'GUN125-3940215',
    location: 'Dar es Salaam Yard',
    price: '34,500',
    photo: 'https://picsum.photos/seed/toyota-hilux-gun125-front/800/600',
    images: [
      'https://picsum.photos/seed/toyota-hilux-gun125-front/800/600',
      'https://picsum.photos/seed/toyota-hilux-gun125-side/800/600',
      'https://picsum.photos/seed/toyota-hilux-gun125-cockpit/800/600',
      'https://picsum.photos/seed/toyota-hilux-gun125-rear/800/600',
      'https://picsum.photos/seed/toyota-hilux-gun125-engine/800/600'
    ],
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '5',
    seats: '5',
    bodyType: 'Pickup',
    features: 'Bluetooth Airbags CD Player Alloy Wheels Fog Lamps 4WD Reverse Camera',
    engine: '2390 CC',
    mileage: '45,700 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1002',
    make: 'Toyota',
    model: 'Land Cruiser Prado TX-L',
    year: '2019',
    chassis: 'GDJ150-0042189',
    location: 'Dar es Salaam Yard',
    price: '46,800',
    photo: 'https://picsum.photos/seed/prado-txl-gdj150-front/800/600',
    images: [
      'https://picsum.photos/seed/prado-txl-gdj150-front/800/600',
      'https://picsum.photos/seed/prado-txl-gdj150-side/800/600',
      'https://picsum.photos/seed/prado-txl-gdj150-interior/800/600',
      'https://picsum.photos/seed/prado-txl-gdj150-seats/800/600',
      'https://picsum.photos/seed/prado-txl-gdj150-rear/800/600'
    ],
    color: 'PEARL WHITE',
    fuel: 'DIESEL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Sunroof Leather Seats Push Start Cool Box 4WD Alloy Wheels',
    engine: '2770 CC',
    mileage: '38,200 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1003',
    make: 'Toyota',
    model: 'Land Cruiser V8 ZX',
    year: '2018',
    chassis: 'URJ202-4019283',
    location: 'Dar es Salaam Yard',
    price: '68,500',
    photo: 'https://picsum.photos/seed/land-cruiser-v8-urj202-front/800/600',
    images: [
      'https://picsum.photos/seed/land-cruiser-v8-urj202-front/800/600',
      'https://picsum.photos/seed/land-cruiser-v8-urj202-side/800/600',
      'https://picsum.photos/seed/land-cruiser-v8-urj202-cockpit/800/600',
      'https://picsum.photos/seed/land-cruiser-v8-urj202-rear/800/600',
      'https://picsum.photos/seed/land-cruiser-v8-urj202-sunroof/800/600'
    ],
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '8',
    bodyType: 'SUV',
    features: 'Height Control Multi-Terrain Select Sunroof Rear Entertainment 360 Camera',
    engine: '4600 CC',
    mileage: '52,100 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1004',
    make: 'Toyota',
    model: 'Harrier Elegance',
    year: '2017',
    chassis: 'ZSU60-0104821',
    location: 'Dar es Salaam Yard',
    price: '22,400',
    photo: 'https://picsum.photos/seed/harrier-zsu60-front/800/600',
    images: [
      'https://picsum.photos/seed/harrier-zsu60-front/800/600',
      'https://picsum.photos/seed/harrier-zsu60-side/800/600',
      'https://picsum.photos/seed/harrier-zsu60-interior/800/600',
      'https://picsum.photos/seed/harrier-zsu60-rear/800/600'
    ],
    color: 'WINE RED',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Half Leather Power Seats Radar Cruise Control LED Headlamps Lane Assist',
    engine: '1980 CC',
    mileage: '49,800 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1005',
    make: 'Toyota',
    model: 'RAV4 Adventure',
    year: '2020',
    chassis: 'MXAA54-2019482',
    location: 'Dar es Salaam Yard',
    price: '29,800',
    photo: 'https://picsum.photos/seed/rav4-mxaa54-front/800/600',
    images: [
      'https://picsum.photos/seed/rav4-mxaa54-front/800/600',
      'https://picsum.photos/seed/rav4-mxaa54-side/800/600',
      'https://picsum.photos/seed/rav4-mxaa54-interior/800/600',
      'https://picsum.photos/seed/rav4-mxaa54-rear/800/600'
    ],
    color: 'GREY',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Dynamic Torque AWD Roof Bars Digital Display Keyless Apple CarPlay',
    engine: '1990 CC',
    mileage: '33,400 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1006',
    make: 'Toyota',
    model: 'Alphard Executive Lounge',
    year: '2016',
    chassis: 'GGH30-0019284',
    location: 'Mwanza Yard',
    price: '33,500',
    photo: 'https://picsum.photos/seed/alphard-ggh30/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'Van',
    features: 'Captain Seats Ottoman Dual Sunroof Power Sliding Doors JBL Premium Audio',
    engine: '3450 CC',
    mileage: '61,200 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1007',
    make: 'SCANIA',
    model: 'R450 Topline Prime Mover',
    year: '2017',
    chassis: 'YS2R4X2000-5421',
    location: 'Dar es Salaam Port',
    price: '48,000',
    photo: 'https://picsum.photos/seed/scania-r450-truck/400/300',
    color: 'BLUE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: 'Opticruise Retarder Double Bunk Sleeping Cab Air Suspension Long Range Tanks',
    engine: '12700 CC',
    mileage: '420,000 KM',
    trans: 'Semi-Auto',
    steering: 'RIGHT',
    status: 'In Transit'
  },
  {
    id: '1008',
    make: 'SCANIA',
    model: 'G460 6x4 Heavy Hauler',
    year: '2016',
    chassis: 'YS2G6X4000-8819',
    location: 'Mwanza Yard',
    price: '54,500',
    photo: 'https://picsum.photos/seed/scania-g460-6x4/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: 'Heavy Duty Hub Reduction Bogie Lift Retarder Bullbar PTO Hydraulics',
    engine: '12740 CC',
    mileage: '380,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1009',
    make: 'SINO',
    model: 'HOWO 371 Tipper 10-Wheeler',
    year: '2021',
    chassis: 'ZZ3257N3847A-1029',
    location: 'Mwanza Yard',
    price: '41,000',
    photo: 'https://picsum.photos/seed/howo-tipper-371/400/300',
    color: 'RED',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: 'Reinforced U-Shape Bucket 20CBM Air Conditioning Heavy Suspension',
    engine: '9726 CC',
    mileage: '65,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1010',
    make: 'Hino',
    model: 'Ranger 8-Tonne Dump Truck',
    year: '2015',
    chassis: 'FC9JAA-10294',
    location: 'Mwanza Yard',
    price: '27,500',
    photo: 'https://picsum.photos/seed/hino-ranger-dump/400/300',
    color: 'GREEN',
    fuel: 'DIESEL',
    doors: '2',
    seats: '3',
    bodyType: 'Heavy Truck',
    features: 'High-lift Hydraulic Tipper Exhaust Brake Power Steering Leaf Suspension',
    engine: '6400 CC',
    mileage: '112,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1011',
    make: 'Nissan',
    model: 'Patrol Y62 Titanium V8',
    year: '2018',
    chassis: 'TNK62-0019284',
    location: 'Mwanza Yard',
    price: '58,000',
    photo: 'https://picsum.photos/seed/nissan-patrol-y62/400/300',
    color: 'SILVER',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Hydraulic Body Motion Control Bose Audio 360 Camera Rear Screens Sunroof',
    engine: '5600 CC',
    mileage: '68,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1012',
    make: 'Nissan',
    model: 'X-Trail 20X Emergency Brake',
    year: '2017',
    chassis: 'NT32-054921',
    location: 'Mwanza Yard',
    price: '14,800',
    photo: 'https://picsum.photos/seed/nissan-xtrail-t32/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: '4WD Mode Selector Heated Seats Around View Monitor Panoramic Roof',
    engine: '1990 CC',
    mileage: '54,200 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1013',
    make: 'Nissan',
    model: 'Navara NP300 4x4 Double Cab',
    year: '2019',
    chassis: 'D23-1029482',
    location: 'Mwanza Yard',
    price: '28,900',
    photo: 'https://picsum.photos/seed/nissan-navara-np300/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '4',
    seats: '5',
    bodyType: 'Pickup',
    features: 'Twin Turbo Canopy Bedliner Alloy Wheels Cruise Control Side Steps',
    engine: '2290 CC',
    mileage: '42,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1014',
    make: 'Mitsubishi',
    model: 'Pajero Exceed 4WD',
    year: '2015',
    chassis: 'V98W-0192847',
    location: 'Mwanza Yard',
    price: '24,200',
    photo: 'https://picsum.photos/seed/mitsubishi-pajero-v98w/400/300',
    color: 'SILVER',
    fuel: 'DIESEL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Super Select 4WD-II Rockford Fosgate Sound Leather Seats Diff Lock',
    engine: '3200 CC',
    mileage: '78,400 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1015',
    make: 'Mitsubishi',
    model: 'Canter Tipper 3-Ton',
    year: '2016',
    chassis: 'FEA50-019284',
    location: 'Mwanza Yard',
    price: '19,500',
    photo: 'https://picsum.photos/seed/canter-tipper-fea50/400/300',
    color: 'BLUE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '3',
    bodyType: 'Heavy Truck',
    features: 'Hydraulic Dump Bed 4P10 Turbo Diesel Power Windows Strong Suspension',
    engine: '2990 CC',
    mileage: '89,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1016',
    make: 'Toyota',
    model: 'Vellfire 2.4Z Golden Eyes',
    year: '2013',
    chassis: 'ANH20-8202764',
    location: 'Mwanza Yard',
    price: '21,500',
    photo: 'https://picsum.photos/seed/toyota-vellfire-anh20/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'Van',
    features: 'Bluetooth Airbags CD Player Alloy Wheels Power Windows Fog Lamps Dual Sunroof',
    engine: '2400 CC',
    mileage: '45,780 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1017',
    make: 'Toyota',
    model: 'Land Cruiser 79 Double Cab',
    year: '2021',
    chassis: 'GRJ79-0019284',
    location: 'Mwanza Yard',
    price: '52,000',
    photo: 'https://picsum.photos/seed/lc79-double-cab/400/300',
    color: 'BEIGE',
    fuel: 'DIESEL',
    doors: '4',
    seats: '5',
    bodyType: 'Pickup',
    features: 'Snorkel Heavy Duty Winch Dual Fuel Tanks Front & Rear Diff Locks Steel Bumper',
    engine: '4500 CC',
    mileage: '24,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1018',
    make: 'Toyota',
    model: 'Coaster Bus 30-Seater',
    year: '2016',
    chassis: 'XZB50-0019482',
    location: 'Mwanza Yard',
    price: '38,500',
    photo: 'https://picsum.photos/seed/toyota-coaster-xzb50/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '30',
    bodyType: 'Bus',
    features: 'Automatic Passenger Door High Ceiling Individual AC Vents Microphone System',
    engine: '4000 CC',
    mileage: '95,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1019',
    make: 'Toyota',
    model: 'HiAce Commuter Grand Cabin',
    year: '2017',
    chassis: 'TRH224-0019482',
    location: 'Mwanza Yard',
    price: '23,800',
    photo: 'https://picsum.photos/seed/hiace-grand-cabin/400/300',
    color: 'GOLD',
    fuel: 'PETROL',
    doors: '4',
    seats: '14',
    bodyType: 'Van',
    features: 'High Roof Long Wheelbase Rear AC Sliding Door Reclining Seats',
    engine: '2700 CC',
    mileage: '72,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1020',
    make: 'Toyota',
    model: 'Premio 1.8X L-Package',
    year: '2016',
    chassis: 'ZRT260-3109482',
    location: 'Mwanza Yard',
    price: '12,900',
    photo: 'https://picsum.photos/seed/toyota-premio-zrt260/400/300',
    color: 'SILVER',
    fuel: 'PETROL',
    doors: '4',
    seats: '5',
    bodyType: 'Saloon',
    features: 'Wood Grain Trim Push Start Smart Key Power Driver Seat Reverse Camera',
    engine: '1800 CC',
    mileage: '51,400 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1021',
    make: 'Toyota',
    model: 'Allion A15 G-Plus',
    year: '2015',
    chassis: 'NZT260-3029481',
    location: 'Mwanza Yard',
    price: '11,800',
    photo: 'https://picsum.photos/seed/toyota-allion-nzt260/400/300',
    color: 'PEARL WHITE',
    fuel: 'PETROL',
    doors: '4',
    seats: '5',
    bodyType: 'Saloon',
    features: 'Push Start Keyless Entry Fog Lamps Climate Control Alloy Wheels',
    engine: '1500 CC',
    mileage: '58,200 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1022',
    make: 'Toyota',
    model: 'Kluger 2.4S',
    year: '2004',
    chassis: 'ACU20-0115987',
    location: 'Mwanza Yard',
    price: '11,200',
    photo: 'https://picsum.photos/seed/toyota-kluger-acu20/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Bluetooth Airbags CD Player Alloy Wheels Power Windows Central Locking',
    engine: '2400 CC',
    mileage: '45,132 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1023',
    make: 'Toyota',
    model: 'Hilux Surf SSR-X',
    year: '2009',
    chassis: 'TRN215-0026394',
    location: 'Mwanza Yard',
    price: '19,800',
    photo: 'https://picsum.photos/seed/toyota-surf-trn215/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Bluetooth Airbags CD Player Alloy Wheels Fog Lamps Roof Rails',
    engine: '2700 CC',
    mileage: '55,460 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1024',
    make: 'Toyota',
    model: 'Spacio 1.5X',
    year: '2004',
    chassis: 'NZE121-3315652',
    location: 'Mwanza Yard',
    price: '8,700',
    photo: 'https://picsum.photos/seed/toyota-spacio-nze121/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'MPV',
    features: 'Bluetooth Airbags CD Player Fog Lamps Central Locking',
    engine: '1490 CC',
    mileage: '48,484 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1025',
    make: 'Mitsubishi',
    model: 'Rvr 1.8G',
    year: '2014',
    chassis: 'GA4W-0101094',
    location: 'Mwanza Yard',
    price: '13,400',
    photo: 'https://picsum.photos/seed/mitsubishi-rvr-ga4w/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Bluetooth CD Player Alloy Wheels Power Windows Airbags Keyless',
    engine: '1800 CC',
    mileage: '56,700 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1026',
    make: 'Subaru',
    model: 'Forester 2.0XT EyeSight',
    year: '2016',
    chassis: 'SJG-029481',
    location: 'Mwanza Yard',
    price: '18,500',
    photo: 'https://picsum.photos/seed/subaru-forester-sjg/400/300',
    color: 'DARK BLUE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Turbo Direct Injection Symmetrical AWD X-Mode EyeSight Safety Dual Exhaust',
    engine: '1998 CC',
    mileage: '63,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1027',
    make: 'Subaru',
    model: 'Outback 2.5i Limited',
    year: '2017',
    chassis: 'BS9-019482',
    location: 'Mwanza Yard',
    price: '20,200',
    photo: 'https://picsum.photos/seed/subaru-outback-bs9/400/300',
    color: 'BROWN',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'T Wagon',
    features: 'Power Liftgate Harman Kardon Sound Leather Heated Seats Roof Rails',
    engine: '2490 CC',
    mileage: '49,800 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1028',
    make: 'Land Rover',
    model: 'Range Rover Sport HSE Dynamic',
    year: '2017',
    chassis: 'SALWA2VF8HA-9182',
    location: 'Mwanza Yard',
    price: '58,000',
    photo: 'https://picsum.photos/seed/range-rover-sport-hse/400/300',
    color: 'GREY',
    fuel: 'DIESEL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Panoramic Roof Meridian Audio Air Suspension Soft Close Doors 21-inch Alloys',
    engine: '2993 CC',
    mileage: '58,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1029',
    make: 'Land Rover',
    model: 'Defender 110 TD5 Adventure',
    year: '2014',
    chassis: 'SALLDHMS8EA-1029',
    location: 'Mwanza Yard',
    price: '44,000',
    photo: 'https://picsum.photos/seed/defender-110-adventure/400/300',
    color: 'ARMY GREEN',
    fuel: 'DIESEL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Heavy Duty Roof Rack Snorkel Rear Ladder Warn Winch Mud-Terrain Tyres',
    engine: '2402 CC',
    mileage: '74,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1030',
    make: 'Mercedes-Benz',
    model: 'Actros 3340 Heavy Prime Mover',
    year: '2016',
    chassis: 'WDB9340322L-9482',
    location: 'Dar es Salaam Port',
    price: '59,000',
    photo: 'https://picsum.photos/seed/mercedes-actros-3340/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: 'V6 Turbo Intercooler Hub Reduction Telligent Gearbox Dual Bunk Sleeper',
    engine: '11946 CC',
    mileage: '490,000 KM',
    trans: 'Semi-Auto',
    steering: 'RIGHT',
    status: 'In Transit'
  },
  {
    id: '1031',
    make: 'Mercedes-Benz',
    model: 'C200 AMG Line Saloon',
    year: '2018',
    chassis: 'WDD2050422R-1029',
    location: 'Mwanza Yard',
    price: '27,500',
    photo: 'https://picsum.photos/seed/mercedes-c200-amg/400/300',
    color: 'POLAR WHITE',
    fuel: 'PETROL',
    doors: '4',
    seats: '5',
    bodyType: 'Saloon',
    features: 'Burmester Surround Sound AMG Body Styling Panoramic Sunroof Ambient Lighting',
    engine: '1991 CC',
    mileage: '43,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1032',
    make: 'BMW',
    model: 'X5 xDrive35d M Sport',
    year: '2017',
    chassis: 'WBAKS420300-4829',
    location: 'Mwanza Yard',
    price: '39,000',
    photo: 'https://picsum.photos/seed/bmw-x5-msport/400/300',
    color: 'SPACE GREY',
    fuel: 'DIESEL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'M Aero Package Panoramic Sunroof Harman Kardon 3rd Row Seats Head-Up Display',
    engine: '2993 CC',
    mileage: '59,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1033',
    make: 'Isuzu',
    model: 'D-Max 4x4 Double Cab V-Cross',
    year: '2020',
    chassis: 'MP1TFR87J-10294',
    location: 'Mwanza Yard',
    price: '33,000',
    photo: 'https://picsum.photos/seed/isuzu-dmax-vcross/400/300',
    color: 'ORANGE',
    fuel: 'DIESEL',
    doors: '4',
    seats: '5',
    bodyType: 'Pickup',
    features: '3.0 Ddi Blue Power Terrain Command 4WD Rollbar Side Steps Touchscreen',
    engine: '2999 CC',
    mileage: '36,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1034',
    make: 'Isuzu',
    model: 'Forward FRR 10-Tonne Cargo Truck',
    year: '2015',
    chassis: 'FRR90S2-019284',
    location: 'Mwanza Yard',
    price: '31,500',
    photo: 'https://picsum.photos/seed/isuzu-forward-frr/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '3',
    bodyType: 'Heavy Truck',
    features: 'Drop Side Wooden Body 6HK1 Engine Heavy Duty Springs Sleeper Cabin',
    engine: '7790 CC',
    mileage: '145,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1035',
    make: 'Suzuki',
    model: 'Jimny Sierra 4WD',
    year: '2021',
    chassis: 'JB74W-102948',
    location: 'Mwanza Yard',
    price: '22,000',
    photo: 'https://picsum.photos/seed/suzuki-jimny-jb74/400/300',
    color: 'KINETIC YELLOW',
    fuel: 'PETROL',
    doors: '3',
    seats: '4',
    bodyType: 'SUV',
    features: 'ALLGRIP PRO 4WD High/Low Ratio Ladder Frame Cruise Control Roof Rails',
    engine: '1460 CC',
    mileage: '18,500 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1036',
    make: 'Toyota',
    model: 'Fortuner 2.8 D-4D 4x4',
    year: '2019',
    chassis: 'GUN156-001928',
    location: 'Mwanza Yard',
    price: '41,500',
    photo: 'https://picsum.photos/seed/toyota-fortuner-gun156/400/300',
    color: 'SILVER',
    fuel: 'DIESEL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Leather Interior Paddle Shifters Power Tailgate Rear AC Diff Lock',
    engine: '2755 CC',
    mileage: '41,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1037',
    make: 'Toyota',
    model: 'Noah Si WxB Edition',
    year: '2017',
    chassis: 'ZRR80-029481',
    location: 'Mwanza Yard',
    price: '17,800',
    photo: 'https://picsum.photos/seed/toyota-noah-zrr80/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '8',
    bodyType: 'Van',
    features: 'Dual Power Sliding Doors Flip-Down Monitor LED Headlamps Smart Key',
    engine: '1986 CC',
    mileage: '53,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1038',
    make: 'Toyota',
    model: 'Voxy ZS Kirameki',
    year: '2018',
    chassis: 'ZRR85-001928',
    location: 'Mwanza Yard',
    price: '18,900',
    photo: 'https://picsum.photos/seed/toyota-voxy-zrr85/400/300',
    color: 'PEARL WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'Van',
    features: 'Aero Package 4WD Dual Sliding Doors Rear View Camera Captain Seats',
    engine: '1986 CC',
    mileage: '47,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1039',
    make: 'Toyota',
    model: 'Crown Athlete G-Package',
    year: '2016',
    chassis: 'ARS210-001928',
    location: 'Mwanza Yard',
    price: '21,000',
    photo: 'https://picsum.photos/seed/toyota-crown-ars210/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '4',
    seats: '5',
    bodyType: 'Saloon',
    features: 'Turbo Direct Injection Soft Close Doors Leather Seats Swing AC Vents',
    engine: '1998 CC',
    mileage: '52,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1040',
    make: 'Toyota',
    model: 'Vanguard 240S 7-Seater',
    year: '2012',
    chassis: 'ACA33-019284',
    location: 'Mwanza Yard',
    price: '14,200',
    photo: 'https://picsum.photos/seed/toyota-vanguard-aca33/400/300',
    color: 'WINE RED',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Active Torque Control 4WD Roof Rails Push Start Alloy Wheels',
    engine: '2360 CC',
    mileage: '69,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1041',
    make: 'Toyota',
    model: 'Probox F 4WD',
    year: '2019',
    chassis: 'NCP165-001928',
    location: 'Mwanza Yard',
    price: '9,800',
    photo: 'https://picsum.photos/seed/toyota-probox-ncp165/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'T Wagon',
    features: '4WD Drive System Air Conditioning Power Front Windows Flat Cargo Floor',
    engine: '1490 CC',
    mileage: '61,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1042',
    make: 'Toyota',
    model: 'Succeed TX Commercial',
    year: '2018',
    chassis: 'NCP160-002918',
    location: 'Mwanza Yard',
    price: '9,400',
    photo: 'https://picsum.photos/seed/toyota-succeed-ncp160/400/300',
    color: 'SILVER',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'T Wagon',
    features: 'Rear Fold-down Seats Durable Fabric AC Roof Rack Ready',
    engine: '1496 CC',
    mileage: '64,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1043',
    make: 'Toyota',
    model: 'Rush G 4WD',
    year: '2015',
    chassis: 'J210E-001928',
    location: 'Mwanza Yard',
    price: '11,500',
    photo: 'https://picsum.photos/seed/toyota-rush-j210e/400/300',
    color: 'PEARL WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Full-Time 4WD Diff Lock Switch High Ground Clearance Roof Bars',
    engine: '1495 CC',
    mileage: '58,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1044',
    make: 'Toyota',
    model: 'Passo Moda Charming Edition',
    year: '2019',
    chassis: 'M700A-001928',
    location: 'Mwanza Yard',
    price: '7,900',
    photo: 'https://picsum.photos/seed/toyota-passo-m700a/400/300',
    color: 'ROSE PINK',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'Hatchback',
    features: 'Fuel Efficient Eco IDLE Push Start Smart Assist Reverse Camera',
    engine: '996 CC',
    mileage: '32,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1045',
    make: 'Nissan',
    model: 'Serena Highway Star S-Hybrid',
    year: '2017',
    chassis: 'C27-019284',
    location: 'Mwanza Yard',
    price: '16,200',
    photo: 'https://picsum.photos/seed/nissan-serena-c27/400/300',
    color: 'BLUE',
    fuel: 'HYBRID',
    doors: '5',
    seats: '8',
    bodyType: 'Van',
    features: 'ProPILOT Autonomous Assist Dual Sliding Doors Split Tailgate Dual AC',
    engine: '1997 CC',
    mileage: '57,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1046',
    make: 'Nissan',
    model: 'Note e-POWER Medalist',
    year: '2018',
    chassis: 'HE12-019284',
    location: 'Mwanza Yard',
    price: '9,800',
    photo: 'https://picsum.photos/seed/nissan-note-he12/400/300',
    color: 'WHITE',
    fuel: 'HYBRID',
    doors: '5',
    seats: '5',
    bodyType: 'Hatchback',
    features: '100% Electric Motor Drive Instant Torque Smart Rearview Mirror Around View',
    engine: '1198 CC',
    mileage: '41,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1047',
    make: 'Mitsubishi',
    model: 'Outlander PHEV 4WD',
    year: '2016',
    chassis: 'GG2W-019284',
    location: 'Mwanza Yard',
    price: '17,500',
    photo: 'https://picsum.photos/seed/outlander-phev-gg2w/400/300',
    color: 'WHITE',
    fuel: 'HYBRID',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Twin Motor 4WD S-AWC EV Mode Heated Seats Leather Power Tailgate',
    engine: '1998 CC',
    mileage: '62,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1048',
    make: 'Mitsubishi',
    model: 'Rosa Bus 29-Seater',
    year: '2015',
    chassis: 'BE64DJ-019284',
    location: 'Mwanza Yard',
    price: '34,000',
    photo: 'https://picsum.photos/seed/mitsubishi-rosa-bus/400/300',
    color: 'WHITE & BLUE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '29',
    bodyType: 'Bus',
    features: 'Air Conditioned Overhead Luggage Racks High Back Seats Exhaust Brake',
    engine: '4899 CC',
    mileage: '118,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1049',
    make: 'Subaru',
    model: 'XV Crosstrek 2.0i-L',
    year: '2018',
    chassis: 'GT7-019284',
    location: 'Mwanza Yard',
    price: '19,200',
    photo: 'https://picsum.photos/seed/subaru-xv-gt7/400/300',
    color: 'COOL GREY KHAKI',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Symmetrical AWD 220mm Clearance EyeSight Apple CarPlay 18-inch Alloys',
    engine: '1995 CC',
    mileage: '39,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1050',
    make: 'Volkswagen',
    model: 'Tiguan R-Line 4Motion',
    year: '2017',
    chassis: 'WVWZZZ5NZHW-1029',
    location: 'Mwanza Yard',
    price: '23,500',
    photo: 'https://picsum.photos/seed/vw-tiguan-rline/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Digital Cockpit Panoramic Sunroof 4Motion AWD R-Line Leather Seats',
    engine: '1984 CC',
    mileage: '46,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1051',
    make: 'Hino',
    model: '500 Series 14-Tonne Cargo',
    year: '2017',
    chassis: 'FG8J-019284',
    location: 'Mwanza Yard',
    price: '42,000',
    photo: 'https://picsum.photos/seed/hino-500-cargo/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '3',
    bodyType: 'Heavy Truck',
    features: 'J08E Engine Heavy Duty Cargo Body Sleeper Cab Air Brakes',
    engine: '7684 CC',
    mileage: '162,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1052',
    make: 'Toyota',
    model: 'Land Cruiser Prado TX 2.7',
    year: '2014',
    chassis: 'TRJ150-008192',
    location: 'Mwanza Yard',
    price: '34,000',
    photo: 'https://picsum.photos/seed/prado-trj150-2014/400/300',
    color: 'PEARL WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: '4WD High/Low 7-Seater Roof Rails Sunroof Push Start Alloy Wheels',
    engine: '2690 CC',
    mileage: '67,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1053',
    make: 'Toyota',
    model: 'Land Cruiser 200 VX Limited',
    year: '2015',
    chassis: 'URJ202-004918',
    location: 'Mwanza Yard',
    price: '52,500',
    photo: 'https://picsum.photos/seed/lc200-vx-limited/400/300',
    color: 'WHITE',
    fuel: 'PETROL',
    doors: '5',
    seats: '8',
    bodyType: 'SUV',
    features: 'Kinetic Dynamic Suspension Cool Box Leather Electric Seats JBL Audio',
    engine: '4608 CC',
    mileage: '71,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1054',
    make: 'Toyota',
    model: 'Hilux Extra Cab 4x4',
    year: '2018',
    chassis: 'GUN126-001928',
    location: 'Mwanza Yard',
    price: '26,500',
    photo: 'https://picsum.photos/seed/hilux-extra-cab/400/300',
    color: 'SILVER',
    fuel: 'DIESEL',
    doors: '2',
    seats: '4',
    bodyType: 'Pickup',
    features: 'Extended Bed Space 4WD Selector Heavy Suspension Tow Hitch',
    engine: '2393 CC',
    mileage: '54,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1055',
    make: 'Nissan',
    model: 'Civilian Bus 30-Seater',
    year: '2016',
    chassis: 'W41-019284',
    location: 'Mwanza Yard',
    price: '32,000',
    photo: 'https://picsum.photos/seed/nissan-civilian-bus/400/300',
    color: 'WHITE & RED',
    fuel: 'DIESEL',
    doors: '2',
    seats: '30',
    bodyType: 'Bus',
    features: 'TD42 Diesel Engine Robust Suspension Air Conditioning PA System',
    engine: '4169 CC',
    mileage: '124,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1056',
    make: 'Honda',
    model: 'CR-V 4WD Masterpiece',
    year: '2019',
    chassis: 'RW2-001928',
    location: 'Mwanza Yard',
    price: '27,000',
    photo: 'https://picsum.photos/seed/honda-crv-rw2/400/300',
    color: 'BLACK',
    fuel: 'PETROL',
    doors: '5',
    seats: '7',
    bodyType: 'SUV',
    features: 'Panoramic Roof Honda SENSING Brown Leather 3rd Row Seats Handsfree Tailgate',
    engine: '1496 CC',
    mileage: '36,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1057',
    make: 'Mazda',
    model: 'CX-5 2.2 XD L-Package AWD',
    year: '2018',
    chassis: 'KF2P-019284',
    location: 'Mwanza Yard',
    price: '21,800',
    photo: 'https://picsum.photos/seed/mazda-cx5-kf2p/400/300',
    color: 'SOUL RED CRYSTAL',
    fuel: 'DIESEL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'i-ACTIV AWD Bose 10-Speaker Audio White Leather Head-Up Display Sunroof',
    engine: '2188 CC',
    mileage: '48,000 KM',
    trans: 'Auto',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1058',
    make: 'SCANIA',
    model: 'P360 6x4 Tipper Truck',
    year: '2015',
    chassis: 'YS2P6X4000-1928',
    location: 'Mwanza Yard',
    price: '46,500',
    photo: 'https://picsum.photos/seed/scania-p360-tipper/400/300',
    color: 'YELLOW',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: '18 Cubic Meter Hardox Steel Body Heavy Duty Axles Hub Reduction Air Seat',
    engine: '12740 CC',
    mileage: '240,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  },
  {
    id: '1059',
    make: 'SINO',
    model: 'Sinotruk A7 6x4 Tractor Head',
    year: '2020',
    chassis: 'ZZ4257V3247N1-92',
    location: 'Dar es Salaam Port',
    price: '43,000',
    photo: 'https://picsum.photos/seed/sinotruk-a7-tractor/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '2',
    seats: '2',
    bodyType: 'Heavy Truck',
    features: 'High Roof Double Sleeper 420HP Engine Heavy Jost 5th Wheel Air Suspension',
    engine: '11596 CC',
    mileage: '78,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Transit'
  },
  {
    id: '1060',
    make: 'Toyota',
    model: 'Land Cruiser 76 Hardtop LX',
    year: '2020',
    chassis: 'GRJ76-001928',
    location: 'Mwanza Yard',
    price: '49,500',
    photo: 'https://picsum.photos/seed/lc76-hardtop-grj76/400/300',
    color: 'WHITE',
    fuel: 'DIESEL',
    doors: '5',
    seats: '5',
    bodyType: 'SUV',
    features: 'Classic 70-Series Front Face Snorkel Electric Winch 4x4 High/Low Mud Tires',
    engine: '4164 CC',
    mileage: '29,000 KM',
    trans: 'Manual',
    steering: 'RIGHT',
    status: 'In Stock'
  }
];

/**
 * Returns a guaranteed array of high-resolution images for any vehicle (minimum 4 viewing angles)
 */
export function getVehicleImages(car) {
  if (!car) return [];
  
  // 1. If explicit images array is provided with multiple images, return it
  if (Array.isArray(car.images) && car.images.length > 0) {
    const valid = car.images.filter(Boolean);
    if (valid.length > 1) {
      return valid;
    }
  }

  // 2. Base photo or fallback
  const primary = (Array.isArray(car.images) && car.images[0]) || car.photo;
  
  if (!primary) {
    const seed = encodeURIComponent(`${car.make || 'toyota'}-${car.model || 'vehicle'}-${car.id || '1000'}`);
    return [
      `https://picsum.photos/seed/${seed}-front/800/600`,
      `https://picsum.photos/seed/${seed}-side/800/600`,
      `https://picsum.photos/seed/${seed}-interior/800/600`,
      `https://picsum.photos/seed/${seed}-rear/800/600`
    ];
  }

  // If using picsum seeded images, generate complementary angles
  if (primary.includes('picsum.photos/seed/')) {
    const seedMatch = primary.match(/\/seed\/([^/]+)/);
    const rawSeed = seedMatch ? seedMatch[1].replace(/-(front|side|rear|interior|seats|cockpit|engine)$/, '') : `${car.make}-${car.model}`;
    return [
      primary,
      `https://picsum.photos/seed/${rawSeed}-side/800/600`,
      `https://picsum.photos/seed/${rawSeed}-interior/800/600`,
      `https://picsum.photos/seed/${rawSeed}-rear/800/600`,
      `https://picsum.photos/seed/${rawSeed}-seats/800/600`
    ];
  }

  // If a single custom image is uploaded, return it as the first photo, with angle tags
  return [primary];
}

